### ISSUE TITLE
Using count returns an error from ElasticSearch

### ISSUE THREAD

**Issue by el-barto** [josegonzalez/cakephp-elastic-search-datasource#37]
I'm trying to count documents from a type called `ix_resources` in my index called `my_index`. Here's a sample code:

```
        var_dump($this->IxResource->find('count'));

        var_dump($this->IxResource->find('count', array(
            'conditions' => array(
                'IxResource.resource_type' => 2,
            )
        )));
```

In both cases the printed result is 0, which is wrong. I did a little debugging of ElasticSearch's response, and I see that while the value of `_count` in the result is zero, I'm getting error messages likes these from every shard:

For the first query:
`BroadcastShardOperationFailedException[[my_index][0] ]; nested: QueryParsingException[[my_index] request does not support [match_all]];`

For the second one:
`BroadcastShardOperationFailedException[[my_index][0] ]; nested: QueryParsingException[[my_index] request does not support [filtered]];`

I believe it has to do with the way the query needs to be constructed for the [Count API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html).

I think there are two things to improve here: 
a) The way the count queries are built 
b) Error handling, because no exception was raised in my tests.

**Comment by josegonzalez** [comment]
I'm going to guess you are using elasticsearch 2.x.

This plugin does not work under ES 2.x, nor do I use it in production anymore. Pull requests to documentation/the code are welcome to fix support for this new version, but I do not expect to continue maintaining the code otherwise. Sorry.

Please upgrade to CakePHP 3.x, where there is an officially supported ElasticSearch module.
